version: '3.7'

services:
  backend:
    image: 'balaji142857/finman:1.0'
    container_name: finman
    build:
      context: ./backend
      args:
        JAR_FILE: build/libs/finance-manager-1.0-SNAPSHOT.jar
    networks:
      - finman-network
    ports:
      - '8080:8980'
    expose:
      - '8980'
    depends_on:
      - db
  db:
    image: 'balaji142857/finman-db:1.0'
    container_name: finman-db
    build:
      context: ./db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - finman-network
  ui:
    image: 'balaji142857/finman-web:1.0'
    container_name: finman-web
    build:
      context: ./ui
    networks:
      - finman-network
    ports:
      - '4200:80'
    expose:
      - '80'
networks:
  finman-network: {}