server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: "jdbc:postgresql://localhost:5432/finman-db"
    username: postgres
    password: password
    platform: postgres
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
